package coloryr.colormirai.demo.RobotSDK;

import coloryr.colormirai.demo.RobotSDK.pack.PackBase;
import coloryr.colormirai.demo.RobotSDK.pack.from.*;
import coloryr.colormirai.demo.RobotSDK.pack.to.*;

import java.util.HashMap;
import java.util.Map;

public class RobotSDK {
    public static final Map<Byte, Class<? extends PackBase>> PackType = new HashMap<Byte, Class<? extends PackBase>>() {{
        put((byte) 1, BeforeImageUploadPack.class);
        put((byte) 2, BotAvatarChangedPack.class);
        put((byte) 3, BotGroupPermissionChangePack.class);
        put((byte) 4, BotInvitedJoinGroupRequestEventPack.class);
        put((byte) 5, BotJoinGroupEventAPack.class);
        put((byte) 6, BotJoinGroupEventBPack.class);
        put((byte) 7, BotLeaveEventAPack.class);
        put((byte) 8, BotLeaveEventBPack.class);
        put((byte) 9, BotMuteEventPack.class);
        put((byte) 10, BotOfflineEventAPack.class);
        put((byte) 11, BotOfflineEventBPack.class);
        put((byte) 12, BotOfflineEventAPack.class);
        put((byte) 13, BotOfflineEventAPack.class);
        put((byte) 14, BotOfflineEventCPack.class);
        put((byte) 15, BotOnlineEventPack.class);
        put((byte) 16, BotReloginEventPack.class);
        put((byte) 17, BotUnmuteEventPack.class);
        put((byte) 18, FriendAddEventPack.class);
        put((byte) 19, FriendAvatarChangedEventPack.class);
        put((byte) 20, FriendDeleteEventPack.class);
        put((byte) 21, FriendMessagePostSendEventPack.class);
        put((byte) 22, FriendMessagePreSendEventPack.class);
        put((byte) 23, FriendRemarkChangeEventPack.class);
        put((byte) 24, GroupAllowAnonymousChatEventPack.class);
        put((byte) 25, GroupAllowConfessTalkEventPack.class);
        put((byte) 26, GroupAllowMemberInviteEventPack.class);
        put((byte) 27, GroupEntranceAnnouncementChangeEventPack.class);
        put((byte) 28, GroupMessagePostSendEventPack.class);
        put((byte) 29, GroupMessagePreSendEventPack.class);
        put((byte) 30, GroupMuteAllEventPack.class);
        put((byte) 31, GroupNameChangeEventPack.class);
        put((byte) 32, ImageUploadEventAPack.class);
        put((byte) 33, ImageUploadEventBPack.class);
        put((byte) 34, MemberCardChangeEventPack.class);
        put((byte) 35, InviteMemberJoinEventPack.class);
        put((byte) 36, MemberJoinEventPack.class);
        put((byte) 37, MemberJoinRequestEventPack.class);
        put((byte) 38, MemberLeaveEventAPack.class);
        put((byte) 39, MemberLeaveEventBPack.class);
        put((byte) 40, MemberMuteEventPack.class);
        put((byte) 41, MemberPermissionChangeEventPack.class);
        put((byte) 42, MemberSpecialTitleChangeEventPack.class);
        put((byte) 43, MemberUnmuteEventPack.class);
        put((byte) 44, MessageRecallEventAPack.class);
        put((byte) 45, MessageRecallEventBPack.class);
        put((byte) 46, NewFriendRequestEventPack.class);
        put((byte) 47, TempMessagePostSendEventPack.class);
        put((byte) 48, TempMessagePreSendEventPack.class);
        put((byte) 49, GroupMessageEventPack.class);
        put((byte) 50, TempMessageEventPack.class);
        put((byte) 51, FriendMessageEventPack.class);
        put((byte) 52, SendGroupMessagePack.class);
        put((byte) 53, SendGroupPrivateMessagePack.class);
        put((byte) 54, SendFriendMessagePack.class);
        put((byte) 55, GetPack.class);
        put((byte) 56, GetPack.class);
        put((byte) 57, GroupGetMemberInfoPack.class);
        put((byte) 58, GroupGetSettingPack.class);
        put((byte) 59, EventCallPack.class);
        //60-63无
        put((byte) 64, GroupKickMemberPack.class);
        put((byte) 65, GroupMuteMemberPack.class);
        put((byte) 66, GroupUnmuteMemberPack.class);
        put((byte) 67, GroupMuteAllPack.class);
        put((byte) 68, GroupUnmuteAllPack.class);
        put((byte) 69, GroupSetMemberCard.class);
        put((byte) 70, GroupSetNamePack.class);
        put((byte) 71, ReCallMessagePack.class);
        put((byte) 72, FriendInputStatusChangedEventPack.class);
        put((byte) 73, FriendNickChangedEventPack.class);
        //74无
        put((byte) 75, SendGroupImageFilePack.class);
        put((byte) 76, SendGroupPrivateImageFilePack.class);
        put((byte) 77, SendFriendImageFilePack.class);
        put((byte) 78, SendGroupSoundFilePack.class);
        put((byte) 79, MemberJoinRetrieveEventPack.class);
        put((byte) 80, BotJoinGroupEventRetrieveEventPack.class);
        put((byte) 81, NudgedEventPack.class);
        put((byte) 82, NudgedEventPack.class);
        put((byte) 83, SendFriendNudgePack.class);
        put((byte) 84, SendGroupMemberNudgePack.class);
        put((byte) 85, GroupTalkativeChangePack.class);
        put((byte) 86, OtherClientOnlineEventPack.class);
        put((byte) 87, OtherClientOfflineEventPack.class);
        put((byte) 88, OtherClientMessageEventPack.class);
        put((byte) 89, GroupMessageSyncEventPack.class);
        put((byte) 90, GetImageUrlPack.class);
        put((byte) 91, GetMemberInfo.class);
        put((byte) 92, GetFriendInfoPack.class);
        put((byte) 93, SendMusicSharePack.class);
        put((byte) 94, GroupSetEssenceMessagePack.class);
        put((byte) 95, MessageBuffPack.class);
        put((byte) 96, SendFriendDicePack.class);
        put((byte) 97, SendGroupDicePack.class);
        put((byte) 98, SendGroupPrivateDicePack.class);
        put((byte) 99, GroupAddFilePack.class);
        put((byte) 100, GroupDeleteFilePack.class);
        put((byte) 101, GroupGetFilesPack.class);
        put((byte) 102, GroupMoveFilePack.class);
        put((byte) 103, GroupRenameFilePack.class);
        put((byte) 104, GroupAddDirPack.class);
        put((byte) 105, GroupDeleteDirPack.class);
        put((byte) 106, GroupRenameDirPack.class);
        put((byte) 107, GroupDownloadFilePack.class);
        put((byte) 108, GroupSetAdminPack.class);
        put((byte) 109, GroupGetAnnouncementsPack.class);
        put((byte) 110, GroupAddAnnouncementPack.class);
        put((byte) 111, GroupDeleteAnnouncementPack.class);
        put((byte) 112, SendFriendSoundFilePack.class);
        put((byte) 113, GroupDisbandPack.class);
    }};
}
